config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'filter/index'
  get 'finder/index'
  resources :newspapers
  resources :categories
  # get 'root/home'
  get '/newspapers/categories', to: 'newspapers#filter', as: :newspapers_filter
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  # == Attributes =================================================================================

  # == Constants ==================================================================================

  # == Class Methods ==============================================================================

  # == Extensions =================================================================================

  # == Instance Methods ===========================================================================

  # == Relationships ==============================================================================

  has_many :newspapers

  # == Scopes =====================================================================================

  # == Validations ================================================================================

  validates :category, presence: true

  # == Raise errors  ==============================================================================
end

app/models/newspaper.rb
class Newspaper < ApplicationRecord
  # == Attributes =================================================================================

  # == Constants ==================================================================================

  # == Class Methods ==============================================================================

  # == Extensions =================================================================================

  # == Instance Methods ===========================================================================

  # == Relationships ==============================================================================

  belongs_to :category

  # == Scopes =====================================================================================

  # == Validations ================================================================================

  validates :header, :body, :link, :category, presence: true

  # == Raise errors  ==============================================================================
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/controllers/filter_controller.rb
class FilterController < ApplicationController
  def index
    if params[:query]
      @newspapers = Newspaper.where('body LIKE ?', "%#{params[:query]}%")
    else
      @newspapers = Newspaper.where(category_id: params[:category_index])
    end
  end
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def filter
    @newspapers = Newspaper.where(category_id: params[:id])
  end
end

app/controllers/newspapers_controller.rb
class NewspapersController < ApplicationController
  before_action :set_newspaper, only: %i[ show edit update destroy ]

  # GET /newspapers or /newspapers.json
  def index
    @newspapers = Newspaper.all
  end

  # GET /newspapers/1 or /newspapers/1.json
  def show
  end

  # GET /newspapers/new
  def new
    @newspaper = Newspaper.new
  end

  # GET /newspapers/1/edit
  def edit
  end

  # POST /newspapers or /newspapers.json
  def create
    @newspaper = Newspaper.new(newspaper_params)

    respond_to do |format|
      if @newspaper.save
        format.html { redirect_to newspaper_url(@newspaper), notice: "Newspaper was successfully created." }
        format.json { render :show, status: :created, location: @newspaper }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newspapers/1 or /newspapers/1.json
  def update
    respond_to do |format|
      if @newspaper.update(newspaper_params)
        format.html { redirect_to newspaper_url(@newspaper), notice: "Newspaper was successfully updated." }
        format.json { render :show, status: :ok, location: @newspaper }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @newspaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newspapers/1 or /newspapers/1.json
  def destroy
    @newspaper.destroy

    respond_to do |format|
      format.html { redirect_to newspapers_url, notice: "Newspaper was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newspaper
      @newspaper = Newspaper.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def newspaper_params
      params.require(:newspaper).permit(:header, :body, :link, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/filter_helper.rb
module FilterHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/newspapers_helper.rb
module NewspapersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Category:</strong>
    <%= category.category %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/filter/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Newspapers</h1>

<div id="newspapers">
  <% @newspapers.each do |newspaper| %>
    <%= render "shared/card", newspaper: newspaper %>
    <p>
      <%= link_to "Show this newspaper", newspaper %>
    </p>
  <% end %>
</div>

<%= link_to "New newspaper", new_newspaper_path %>

app/views/finder/index.html.erb
<h1>Finder#index</h1>
<p>Find me in app/views/finder/index.html.erb</p>

app/views/home/index.html.erb
<div class="page-preview">
    <div class="page-preview-header">
        <a class="hidden-sm hidden-xs active" href="#" id="previewDesktopBtn" data-preview-size="100%"><img alt="Responsive Desktop Mode" src="//csite.nicepage.com/Images/Site/responsive-desktop.png"></a>
        <a class="hidden-sm hidden-xs" href="#" id="previewLaptopBtn" data-preview-size="1040px"><img alt="Responsive Laptop Mode" src="//csite.nicepage.com/Images/Site/responsive-laptop.png"></a>
        <a class="hidden-xs" href="#" id="previewTabletBtn" data-preview-size="820px"><img alt="Responsive Tablet Mode" src="//csite.nicepage.com/Images/Site/responsive-tablet.png"></a>
        <a class="hidden-xs" href="#" id="previewPhoneHorizontalBtn" data-preview-size="640px"><img alt="Responsive Phone Horizontal Mode" src="//csite.nicepage.com/Images/Site/responsive-phone-horizontal.png"></a>
        <a class="hidden-xs" href="#" id="previewPhoneBtn" data-preview-size="440px"><img alt="Responsive Phone Mode" src="//csite.nicepage.com/Images/Site/responsive-phone.png"></a>
        <a class="close" href="/es/h5/241469/planificacion-de-espacios-de-la-ciudad-plantilla-html5"><img alt="Close" src="//csite.nicepage.com/Images/Site/icon-close.png"></a>
    </div>
    <div class="page-preview-body">
        <iframe id="livePreviewFrame" src="https://architecture.nicepage.io/es/Page-1.html?version=edc63b95-6731-4ec5-84c5-546f9abdbfe5" width="1057" height="640" style="width:100%;"></iframe> 
    </div>   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Noticias2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <!-- Bootstrap CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render('shared/navbar') %>
    <%= yield %>
    
  </body>
</html>

app/views/newspapers/_form.html.erb
<%= form_with(model: newspaper) do |form| %>
  <% if newspaper.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(newspaper.errors.count, "error") %> prohibited this newspaper from being saved:</h2>

      <ul>
        <% newspaper.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :header, style: "display: block" %>
    <%= form.text_field :header %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/newspapers/_newspaper.html.erb
<div id="<%= dom_id newspaper %>">
  <p>
    <strong>Header:</strong>
    <%= newspaper.header %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= newspaper.body %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= newspaper.link %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= newspaper.category.category %>
  </p>

</div>

app/views/newspapers/edit.html.erb
<h1>Editing newspaper</h1>

<%= render "form", newspaper: @newspaper %>

<br>

<div>
  <%= link_to "Show this newspaper", @newspaper %> |
  <%= link_to "Back to newspapers", newspapers_path %>
</div>

app/views/newspapers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Newspapers</h1>

<div id="newspapers">
<%= link_to "New newspaper", new_newspaper_path %>
  <% @newspapers.each do |newspaper| %>
    <%= render "shared/card", newspaper: newspaper %>
  <% end %>
</div>

app/views/newspapers/new.html.erb
<h1>New newspaper</h1>

<%= render "form", newspaper: @newspaper %>

<br>

<div>
  <%= link_to "Back to newspapers", newspapers_path %>
</div>

app/views/newspapers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @newspaper %>

<div>
  <%= link_to "Edit this newspaper", edit_newspaper_path(@newspaper) %> |
  <%= link_to "Back to newspapers", newspapers_path %>

  <%= button_to "Destroy this newspaper", @newspaper, method: :delete %>
</div>

app/views/shared/_card.html.erb
<div class="card" style="width: 18rem;">
  <img src="/assets/newspapers" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= newspaper.header %></h5>
    <p class="card-text"><%= newspaper.body[0..150] %> ... </p>
    <%= link_to "Ver mas", newspaper, class: "btn btn-primary", target: "_blank" %>
    <%= link_to "Mostrar más de esta categoría", filter_index_path(category_index: newspaper.category_id), class: "btn btn-primary" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'Inicio', root_path, class: 'navbar-brand'%>
    <%= link_to 'Noticias', newspapers_path, class: 'navbar-brand'%>
    
  
<!--Desplegable-->
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Dropdown</a>
    <ul class="dropdown-menu">
      <%
=begin%>
 <li><%= link_to 'Deportes', , class: 'dropdown-item' %></li>
      <li><%= link_to 'Farándula', , class: 'dropdown-item' %></li>
      <li><%= link_to 'Nacional', , class: 'dropdown-item' %></li>
      <li><%= link_to 'Internacional', , class: 'dropdown-item' %></li>
      <li><%= link_to 'Política', , class: 'dropdown-item' %></li> 
<%
=end%>
    </ul>
  </li>
    
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <%= form_tag filter_index_path, class: 'd-flex', method: :get do %>
        <%= text_field_tag :query, nil, placeholder: 'Buscar', class: 'form-control me-2'%>
        <%= submit_tag "Search", class: 'btn btn-outline-success' %>
      <% end %> 
    </div>
  </div>
</nav>